url: http://jhattat.github.io
baseurl: /HackTheLink/

# Site settings
title: HackTheLink
email: jhattat@agilead.fr
description: "Site du Hackathon GetLink."


# Team names, titles and social links
people:
- name: Nicola Booneart
  pic: nico
  position: Orga, Support & Arhitect
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Celine Grosjean
  pic: celinegrosjean
  position: UX Design
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Romain Yvart
  pic: romain
  position: Project Manager
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Valerie Morel
  pic: val
  position: Graphiste
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Frederic Riga
  pic: fred
  position: Sponsor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Jérémie Hattat
  pic: jay
  position: GO
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# rules
rule:
- title: Prize
  icon: "fa fa-trophy"
  text: Des lots...

- title: Hours
  icon: fa fa-hourglass-start
  text: dddd...

- title: Propiété intellectuelle
  icon: "fas fa-file-contract"
  text: dddd...

- title: Team
  icon: fas fa-users
  text: dddd...

- title: Hours
  icon: hourglass-start
  text: dddd...

- title: Hours
  icon: hourglass-start
  text: dddd...

  # Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty